package org.example.project.runnable.spring.configuration

import org.example.project.adapter.spring.reactive.SpringRestReactiveAutoConfiguration
import org.springframework.boot.autoconfigure.ImportAutoConfiguration
import org.springframework.context.annotation.Configuration

@Configuration
@ImportAutoConfiguration(SpringRestReactiveAutoConfiguration::class)
class SpringRestReactiveAdapterConfiguration