name: Build & Release

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean check
